(C11N) Make submodule paths relative
Attempt to fix:

   Cloning into '/builds/strato-dev/nextcloud-server/custom-apps/enc_analytics'...
   error: cannot run ssh: No such file or directory
   fatal: unable to fork

The relative path prefix "../" is tried first because this is what the man
page says. Another, GitLab related, source said something about
"../../".